[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Djaylano asper a.djaylano@gmail.com"]
requires-python = ">=3.11"
dependencies = [
    "cryptography>=44.0.2",
    "flask>=3.1.0",
    "werkzeug>=3.1.3",
]
